(function(){'use strict';
const R=window.RBX={scenes:{},levels:window.RBX_LEVELS||[]},$=s=>document.querySelector(s);let cv,ctx,W,H,state,idx=0,total=0,wins=0,running=false,won=false,last=performance.now();const keys={};
R.s=()=>state;R.ctx=()=>ctx;R.size=()=>[W,H];R.run=()=>running;R.level=()=>R.levels[idx];
R.rect=(x,y,w,h,c)=>{ctx.fillStyle=c;ctx.fillRect(x,y,w,h)};R.round=(x,y,w,h,r,c)=>{ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()};R.circle=(x,y,r,c)=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()};R.text=(t,x,y,z=16,c='#22283b',a='left')=>{ctx.fillStyle=c;ctx.font='900 '+z+'px '+getComputedStyle(document.body).fontFamily;ctx.textAlign=a;ctx.fillText(t,x,y)};
R.hit=(p,r)=>{const x=Math.max(r.x,Math.min(p.x,r.x+r.w)),y=Math.max(r.y,Math.min(p.y,r.y+r.h));return(p.x-x)**2+(p.y-y)**2<p.r**2};
function base(){return{player:{x:55,y:H/2,r:13,v:150},goal:{x:W-58,y:H/2,w:34,h:70},used:new Set(),t:0,coins:0,order:[],dead:0,style:'default',checkpoint:null,trail:[],lockNotice:false}}
function init(){state=base();running=won=false;const t=R.level().type;if(t==='floor')Object.assign(state,{floorColor:'#aab4bf',floorY:72,floorH:H-144,coinList:[[185,145],[360,300],[540,155]]});if(t==='lava')Object.assign(state,{lavaColor:'#ff4b23',lavaNarrow:false,jumpPad:false,speedPad:false});if(t==='styleRun')Object.assign(state,{lavaColor:'#ff4b23',glass:false,welcome:false,coinList:[]});if(t==='moving')Object.assign(state,{platformX:260,platformDir:1,platformSpeed:170,platformW:95});if(t==='bridge')Object.assign(state,{bridgeLong:false,bridgeTogether:false,safe:false});if(t==='laser')Object.assign(state,{laserPeriod:1.2,disabledLaser:false});if(t==='maze')Object.assign(state,{goalCoins:5,radar:false,showTrail:false,coinList:[[130,92],[300,82],[472,104],[198,365],[620,380]]});if(t==='chase')Object.assign(state,{enemy:{x:W-180,y:95,r:16},enemySpeed:92,hasCore:false,boost:false,safeZones:false,core:{x:W/2,y:H/2}})}
R.msg=h=>{const m=document.createElement('div');m.className='msg';m.innerHTML='<span class="av">🧱</span><div class="bub">'+h+'</div>';$('#chat').appendChild(m);$('#chat').scrollTop=$('#chat').scrollHeight};
function step(n){for(let i=1;i<=4;i++)$('#how'+i).classList.toggle('on',i===n)}
function mode(v){running=v;$('#mode').textContent=v?'🎮 遊玩模式':'🛠 設計模式';$('#mode').className='mode'+(v?' play':'');$('#playBtn').textContent=v?'⏹ 停止測試':'▶ 玩玩看';$('#playBtn').className='btn '+(v?'stopbtn':'playbtn');document.querySelectorAll('.opt').forEach(b=>b.disabled=v);step(v?3:state.used.size?2:1)}
R.resetPlayer=()=>{const p=state.player;if(state.checkpoint){p.x=state.checkpoint.x;p.y=state.checkpoint.y}else{p.x=55;p.y=H/2}p.v=150;if(state.enemy){state.enemy.x=W-180;state.enemy.y=95}};
R.die=t=>{state.dead++;R.resetPlayer();R.msg(t+' 我把你送回起點。想想看，哪一個修改指令可以改善這個問題？')};
R.win=t=>{if(won)return;won=true;running=false;wins++;mode(false);step(4);$('#toastText').textContent=t;$('#toast').classList.add('show');$('#nextBtn').hidden=false;$('#nextBtn').textContent=idx===R.levels.length-1?'查看學習成果 →':'前往第 '+R.levels[idx+1].no+' 關 →';R.msg('測試成功！你完成了<b>修改 → 測試 → 驗證</b>的遊戲設計循環。')};
R.goal=open=>{const g=state.goal;R.round(g.x-g.w/2,g.y-g.h/2,g.w,g.h,5,open?'#39b54a':'#7a879e');R.rect(g.x-4,g.y-g.h/2-18,8,g.h+18,'#191b1d');R.text(open?'終點':'鎖定',g.x,g.y+5,12,'#fff','center')};
R.coins=()=>{(state.coinList||[]).forEach(c=>{if(!c[2]){R.circle(c[0],c[1],11,'#ffd54a');R.text('$',c[0],c[1]+5,13,'#795a00','center');if(running&&Math.hypot(state.player.x-c[0],state.player.y-c[1])<26){c[2]=true;state.coins++;R.msg('你收集到一枚金幣，目前共 <b>'+state.coins+'</b> 枚。')}}})};
R.move=dt=>{if(!running||won)return;const p=state.player,dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0),len=Math.hypot(dx,dy)||1;let v=p.v;if(R.level().type==='chase'&&state.boost&&keys[' '])v=255;p.x+=dx/len*v*dt;p.y+=dy/len*v*dt;p.x=Math.max(18,Math.min(W-18,p.x));p.y=Math.max(18,Math.min(H-18,p.y));state.trail.push([p.x,p.y]);if(state.trail.length>70)state.trail.shift()};
function bg(){let a='#bfe7ff',b='#d7f2ff';if(state.style==='cyber'){a='#151a2a';b='#252d46'}if(state.style==='space'){a='#090d1d';b='#141b35'}if(state.style==='forest'){a='#c7efd0';b='#8fd19e'}if(state.style==='ice'){a='#dff8ff';b='#b9eaf7'}const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(state.style==='space')for(let i=0;i<70;i++)R.circle((i*97)%W,(i*53)%H,(i%3)+1,'rgba(255,255,255,.7)')}
function player(){const p=state.player;R.circle(p.x,p.y,p.r,'#e2231a');R.round(p.x-8,p.y-9,16,13,3,'#fff');R.circle(p.x-4,p.y-3,2,'#191b1d');R.circle(p.x+4,p.y-3,2,'#191b1d')}
function apply(o,b){if(running||state.used.has(o[0]))return;const x=o[0];state.used.add(x);b.classList.add('used');total++;if(x==='skyBig'){state.floorColor='#50b9ff';state.floorY=42;state.floorH=H-84}else if(x==='prairie'){state.floorColor='#55b95f';state.floorY=62;state.floorH=H-124}else if(x==='tinyPad'){state.floorY=176;state.floorH=108}else if(x==='floorCoins')state.coinList.push([270,220],[455,245]);else if(x==='lavaNarrow')state.lavaNarrow=true;else if(x==='jumpPad')state.jumpPad=true;else if(x==='speedPad')state.speedPad=true;else if(x==='poison')state.lavaColor='#8b3dca';else if(x==='glass')state.glass=true;else if(x==='neonLava')state.lavaColor='#00a2ff';else if(x==='welcome')state.welcome=true;else if(x==='extraCoins')state.coinList=[[315,160],[395,300],[475,160]];else if(x==='slow')state.platformSpeed=85;else if(x==='wide')state.platformW=180;else if(x==='checkpoint')state.checkpoint={x:370,y:H/2};else if(x==='neon')state.style='neon';else if(x==='long')state.bridgeLong=true;else if(x==='together')state.bridgeTogether=true;else if(x==='safe')state.safe=true;else if(x==='ice')state.style='ice';else if(x==='hint')state.showHint=true;else if(x==='laserSlow')state.laserPeriod=2.2;else if(x==='oneOff')state.disabledLaser=true;else if(x==='cyber')state.style='cyber';else if(x==='goal3')state.goalCoins=3;else if(x==='trail')state.showTrail=true;else if(x==='radar')state.radar=true;else if(x==='forest')state.style='forest';else if(x==='enemySlow')state.enemySpeed=58;else if(x==='boost')state.boost=true;else if(x==='safeZone')state.safeZones=true;else if(x==='space')state.style='space';$('#counter').textContent='🔧 '+state.used.size;R.msg('修改完成！<b>「'+o[1]+'」</b><br>'+o[2]+' 現在可以按 <b>▶ 玩玩看</b> 測試。');step(2);draw()}
function progress(){const p=$('#progress');p.innerHTML='';R.levels.forEach((l,i)=>{const s=document.createElement('span');s.className='pstep'+(i===idx?' on':i<idx?' done':'');s.textContent='第 '+l.no+' 關';p.appendChild(s);if(i<R.levels.length-1){const a=document.createElement('span');a.className='arrow';a.textContent='›';p.appendChild(a)}})}
function render(){const L=R.level();progress();$('#levelTitle').innerHTML='<b>第 '+L.no+' 關</b>・'+L.title;$('#levelBadge').textContent='🧠 '+L.badge;$('#assistantSub').textContent='第 '+L.no+' 關・'+L.concept;$('#controls').textContent=L.controls;$('#counter').textContent='🔧 0';$('#chat').innerHTML='<div class="task"><b>🎯 任務：'+L.task+'</b><p>'+L.intro+'</p></div><span class="concept">🧠 這關偷偷在學：'+L.concept+'</span><div class="msg"><span class="av">🧱</span><div class="bub">先看看場景，再選一句話修改規則或外觀。完成修改後，按 <b>▶ 玩玩看</b> 親自測試。</div></div><div class="options" id="options"></div>';L.options.forEach(o=>{const b=document.createElement('button');b.className='opt '+(o[3]||'');b.type='button';b.textContent=o[1];b.onclick=()=>apply(o,b);$('#options').appendChild(b)});$('#nextBtn').hidden=true;$('#toast').classList.remove('show');mode(false);draw()}
function draw(dt=0){bg();const f=R.scenes[R.level().type];if(f)f(dt);player()}
function frame(n){const dt=Math.min(.032,(n-last)/1000);last=n;state.t+=dt;if(running&&!won){if(R.level().type!=='maze')R.move(dt);draw(dt)}else draw(0);requestAnimationFrame(frame)}
function result(){$('#gameShell').hidden=true;$('#progress').hidden=true;$('#nextBtn').hidden=true;$('#result').hidden=false;$('#statCommands').textContent=total;$('#statWins').textContent=wins;scrollTo({top:0,behavior:'smooth'})}
R.start=()=>{cv=$('#cv');ctx=cv.getContext('2d');W=cv.width;H=cv.height;$('#playBtn').onclick=()=>{if(won)return;if(running){mode(false);R.msg('已停止測試，可以繼續修改。')}else{mode(true);R.msg('進入遊玩模式。實際跑一次，才知道設計是否真的可行。')}};$('#resetBtn').onclick=()=>{R.resetPlayer();state.order=[];state.coins=0;state.lockNotice=false;(state.coinList||[]).forEach(c=>c[2]=false);state.hasCore=false;R.msg('位置與本次測試資料已重設，遊戲規則修改仍保留。')};$('#nextBtn').onclick=()=>{if(idx<R.levels.length-1){idx++;init();render();scrollTo({top:0,behavior:'smooth'})}else result()};$('#replayBtn').onclick=()=>{idx=total=wins=0;$('#result').hidden=true;$('#gameShell').hidden=false;$('#progress').hidden=false;init();render();scrollTo({top:0,behavior:'smooth'})};addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()},{passive:false});addEventListener('keyup',e=>{keys[e.key.length===1?e.key.toLowerCase():e.key]=false});init();render();requestAnimationFrame(frame)};
})();
