(function(){
'use strict';
const $=s=>document.querySelector(s), levels=window.RBX_LEVELS||[];
const THREE=window.THREE;
const cv=$('#cv'), fallback=$('#fallback');
if(!THREE){ fallback.hidden=false; return; }

let renderer,scene,camera,world,avatar,enemyGroup,flagGroup;
let armL,armR,legL,legR,clock=new THREE.Clock();
let idx=0,totalMods=0,wins=0,running=false,won=false,levelStarted=false;
let state=null,platforms=[],walls=[],coins=[],lasers=[],buttons=[],dynamic=[];
let keys={},yaw=.78,pitch=.48,zoom=35,drag=false,px=0,py=0;
let buildAt=0,buildFrom=0;
const UNIT=new THREE.BoxGeometry(1,1,1);
const playerRadius=.62;

function mat(color,o={}){return new THREE.MeshStandardMaterial({color:new THREE.Color(color),roughness:o.rough??.82,metalness:o.metal??0,transparent:!!o.transparent,opacity:o.opacity??1,emissive:new THREE.Color(o.emissive||0x000000),emissiveIntensity:o.ei||0});}
function shade(color,f){const c=new THREE.Color(color);if(f<0)c.multiplyScalar(1+f);else c.lerp(new THREE.Color(0xffffff),f);return c;}
function box(x,y,z,w,h,d,color,o={}){const m=new THREE.Mesh(UNIT,mat(color,o));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=o.cast!==false;m.receiveShadow=o.receive!==false;world.add(m);return m;}
function platform(x,z,w,d,color,o={}){const h=o.h||1,y=o.y??0;const mesh=box(x,y,z,w,h,d,color,o);const lip=box(x,y-h*.62,z,w+.25,h*.35,d+.25,shade(color,-.2),{cast:false});const p={x,z,w,d,h,y,top:y+h/2,mesh,lip,active:true,id:o.id||'',moving:!!o.moving,dx:0,dz:0};platforms.push(p);return p;}
function wall(x,z,w,d,h=2.4,color='#66758b',o={}){const mesh=box(x,h/2+.5,z,w,h,d,color,o);const v={x,z,w,d,h,mesh,active:true};walls.push(v);return v;}
function canvasTexture(text,bg='#fff8e1',fg='#22283b'){const c=document.createElement('canvas');c.width=512;c.height=180;const g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,c.width,c.height);g.strokeStyle='#22283b';g.lineWidth=14;g.strokeRect(7,7,c.width-14,c.height-14);g.fillStyle=fg;g.font='900 62px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(text,c.width/2,c.height/2);return new THREE.CanvasTexture(c);}
function sign(x,z,text){const g=new THREE.Group();const post=new THREE.Mesh(UNIT,mat('#8a5a2b'));post.scale.set(.22,2.2,.22);post.position.y=1.1;g.add(post);const b=new THREE.Mesh(UNIT,new THREE.MeshStandardMaterial({map:canvasTexture(text),roughness:.65}));b.scale.set(4.4,1.5,.22);b.position.y=2.35;g.add(b);g.position.set(x,.5,z);world.add(g);return g;}
function labelSprite(text,bg='#22283b',fg='#fff'){const c=document.createElement('canvas');c.width=384;c.height=112;const g=c.getContext('2d');g.fillStyle=bg;if(g.roundRect){g.beginPath();g.roundRect(4,4,376,104,28);g.fill();}else g.fillRect(4,4,376,104);g.fillStyle=fg;g.font='900 42px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(text,192,56);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));sp.scale.set(4.8,1.4,1);return sp;}
function addCoin(x,z,y=.95){const g=new THREE.Group();const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.18,24),mat('#ffd23c',{metal:.25,rough:.28,emissive:'#ffb300',ei:.45}));mesh.rotation.x=Math.PI/2;g.add(mesh);const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.08,8,24),mat('#fff2a8',{emissive:'#ffc93c',ei:.5}));g.add(ring);g.position.set(x,y,z);world.add(g);coins.push({x,z,y,group:g,taken:false});return g;}
function addFlag(x,z,open=true){const g=new THREE.Group();const pole=new THREE.Mesh(UNIT,mat('#39415a'));pole.scale.set(.18,4,.18);pole.position.y=2;g.add(pole);const sh=new THREE.Shape();sh.moveTo(0,0);sh.lineTo(1.65,.55);sh.lineTo(0,1.1);sh.closePath();const pen=new THREE.Mesh(new THREE.ExtrudeGeometry(sh,{depth:.08,bevelEnabled:false}),mat(open?'#4cbb5e':'#7a879e'));pen.position.set(.1,3.05,0);g.add(pen);const tag=labelSprite(open?'終點':'鎖定',open?'#4cbb5e':'#7a879e');tag.position.set(0,4.8,0);g.add(tag);g.position.set(x,.5,z);world.add(g);flagGroup=g;return g;}
function setFlag(open){if(!flagGroup)return;const pen=flagGroup.children[1];pen.material.color.set(open?'#4cbb5e':'#7a879e');const old=flagGroup.children[2];flagGroup.remove(old);const tag=labelSprite(open?'終點':'鎖定',open?'#4cbb5e':'#7a879e');tag.position.set(0,4.8,0);flagGroup.add(tag);}
function buildAvatar(){avatar=new THREE.Group();world.add(avatar);avatar.scale.setScalar(1.18);const torsoMat=mat('#ff8c1a',{rough:.7}),headMat=mat('#ffc93c',{rough:.62}),dark=mat('#1a1f31');const torso=new THREE.Mesh(UNIT,torsoMat);torso.scale.set(1.32,1.25,.82);torso.position.y=1.55;avatar.add(torso);const head=new THREE.Mesh(UNIT,headMat);head.scale.set(1.15,1.05,1.02);head.position.y=2.7;avatar.add(head);legL=new THREE.Group();legL.position.set(-.34,.93,0);const lm=new THREE.Mesh(UNIT,dark);lm.scale.set(.42,1,.48);lm.position.y=-.5;legL.add(lm);avatar.add(legL);legR=new THREE.Group();legR.position.set(.34,.93,0);const rm=new THREE.Mesh(UNIT,dark);rm.scale.set(.42,1,.48);rm.position.y=-.5;legR.add(rm);avatar.add(legR);armL=new THREE.Group();armL.position.set(-.92,2.02,0);const am=new THREE.Mesh(UNIT,torsoMat);am.scale.set(.34,1.05,.36);am.position.y=-.52;armL.add(am);avatar.add(armL);armR=new THREE.Group();armR.position.set(.92,2.02,0);const bm=new THREE.Mesh(UNIT,torsoMat);bm.scale.set(.34,1.05,.36);bm.position.y=-.52;armR.add(bm);avatar.add(armR);avatar.traverse(o=>{if(o.isMesh)o.castShadow=true;});}
function buildEnemy(){enemyGroup=new THREE.Group();world.add(enemyGroup);const body=new THREE.Mesh(UNIT,mat('#8b5cf6',{emissive:'#6d3fd4',ei:.28}));body.scale.set(1.6,1.5,1.3);body.position.y=1.35;enemyGroup.add(body);const head=new THREE.Mesh(UNIT,mat('#5b34b4',{emissive:'#8b5cf6',ei:.35}));head.scale.set(1.35,1.1,1.15);head.position.y=2.65;enemyGroup.add(head);for(const x of[-.33,.33]){const eye=new THREE.Mesh(UNIT,mat('#ffc93c',{emissive:'#ffc93c',ei:1}));eye.scale.set(.16,.22,.08);eye.position.set(x,2.78,.61);enemyGroup.add(eye);}enemyGroup.traverse(o=>{if(o.isMesh)o.castShadow=true;});}
function setup3D(){renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene=new THREE.Scene();scene.background=new THREE.Color('#cdeafd');camera=new THREE.PerspectiveCamera(46,1,.1,250);scene.add(new THREE.HemisphereLight(0xffffff,0xcfe6f7,1));scene.add(new THREE.AmbientLight(0xffffff,.22));const sun=new THREE.DirectionalLight(0xffffff,.9);sun.position.set(8,22,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;scene.add(sun);resize();addEventListener('resize',resize);cv.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;cv.setPointerCapture(e.pointerId)});cv.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-px)*.008;pitch=Math.max(.18,Math.min(1.05,pitch+(e.clientY-py)*.006));px=e.clientX;py=e.clientY});cv.addEventListener('pointerup',()=>drag=false);cv.addEventListener('wheel',e=>{zoom=Math.max(24,Math.min(48,zoom+e.deltaY*.02));e.preventDefault()},{passive:false});}
function resize(){const r=cv.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
function updateCamera(){const c=new THREE.Vector3(0,1.3,0),cp=Math.cos(pitch);camera.position.set(c.x+Math.sin(yaw)*cp*zoom,c.y+Math.sin(pitch)*zoom,c.z+Math.cos(yaw)*cp*zoom);camera.lookAt(c);}
function clearWorld(){if(world){scene.remove(world);world.traverse(o=>{if(o.geometry&&o.geometry!==UNIT&&o.geometry.dispose)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose&&m.dispose());else if(o.material.dispose)o.material.dispose();}});}world=new THREE.Group();scene.add(world);platforms=[];walls=[];coins=[];lasers=[];buttons=[];dynamic=[];enemyGroup=flagGroup=null;buildAvatar();}
function baseState(){return{used:new Set(),player:{x:-12,y:.5,z:0,vy:0,grounded:true,speed:7,yaw:0,on:null},goal:{x:13,z:0,open:true},t:0,dead:0,coins:0,order:[],style:'default',firstFail:false,repairUnlocked:false,boostTime:0,checkpoint:null,hasCore:false,enemy:{x:7,z:-5,speed:3.5},core:{x:0,z:0},bridgeLong:false,bridgeTogether:false,safe:false,laserPeriod:1.4,showHint:false,disabledLaser:false,goalCoins:5,showTrail:false,radar:false,safeZones:false,playerBoost:false};}
function initState(){state=baseState();const t=levels[idx].type;if(t==='floor')Object.assign(state,{floorColor:'#aab4bf',floorW:18,floorD:12});if(t==='lava')Object.assign(state,{lavaColor:'#ff4b23',gap:10,lavaNarrow:false,jumpPad:false,speedPad:false});if(t==='styleRun')Object.assign(state,{lavaColor:'#ff4b23',glass:false,welcome:false});if(t==='moving')Object.assign(state,{platformSpeed:4.4,platformW:3.2,platformX:-4.5,platformDir:1});if(t==='bridge')Object.assign(state,{bridgeLong:false,bridgeTogether:false,safe:false});if(t==='laser')Object.assign(state,{laserPeriod:1.35,disabledLaser:false});if(t==='maze')Object.assign(state,{goalCoins:5,showTrail:false,radar:false});if(t==='chase')Object.assign(state,{enemy:{x:8,z:-5,speed:3.4},hasCore:false,safeZones:false,playerBoost:false});}
function startPos(x,z,y){state.player.x=x;state.player.z=z;state.player.y=y;state.player.vy=0;state.player.grounded=true;state.player.on=null;avatar.position.set(x,y,z);}
function buildWorld(drop=1.5){clearWorld();const t=levels[idx].type;scene.background.set(state.style==='space'?'#090d1d':state.style==='cyber'?'#151a2a':'#cdeafd');if(t==='floor')buildFloor();else if(t==='lava')buildLava();else if(t==='styleRun')buildStyle();else if(t==='moving')buildMoving();else if(t==='bridge')buildBridge();else if(t==='laser')buildLaser();else if(t==='maze')buildMaze();else if(t==='chase')buildChase();world.position.y=drop;buildFrom=drop;buildAt=performance.now();updateAvatar(0);}
function buildFloor(){const w=state.used.has('tinyPad')?7:state.used.has('skyBig')?24:state.used.has('prairie')?22:18;const d=state.used.has('tinyPad')?7:state.used.has('skyBig')?17:state.used.has('prairie')?15:12;const c=state.used.has('skyBig')?'#3aa7e8':state.used.has('prairie')?'#4cbb5e':'#aab4bf';platform(0,0,w,d,c);const sx=-w/2+2,gx=w/2-2;state.goal={x:gx,z:0,open:true};startPos(sx,0,.5);addFlag(gx,0,true);[-w*.18,w*.02,w*.22].forEach((x,i)=>addCoin(x,(i-1)*2));}
function buildLava(){const gap=state.used.has('lavaNarrow')?4:10;state.gap=gap;const side=11;platform(-(gap/2+side/2),0,side,14,'#4cbb5e');platform(gap/2+side/2,0,side,14,'#aab4bf');const lava=box(0,-.35,0,gap,.5,14,state.used.has('poison')?'#8b5cf6':'#ff4b23',{emissive:state.used.has('poison')?'#a78bfa':'#ff3b2f',ei:.8});lava.userData.hazard=true;state.lava={x:0,z:0,w:gap,d:14};if(state.used.has('jumpPad'))[-gap*.3,0,gap*.3].forEach((x,i)=>platform(x,(i%2?2:-2),2.5,2.5,'#a98f6f',{h:.7}));if(state.used.has('speedPad')){const p=platform(-gap/2-1.7,0,2.4,5,'#3ad0ff',{h:.18,y:.62,emissive:'#7ff0ff',ei:.85,id:'speed'});p.speedPad=true;}state.goal={x:gap/2+side-2,z:0,open:true};startPos(-gap/2-side+2,0,.5);addFlag(state.goal.x,0,true);addCoin(gap/2+3,-2);addCoin(gap/2+5,2);}
function buildStyle(){platform(-9,0,10,14,'#4cbb5e');platform(9,0,10,14,'#aab4bf');state.lava={x:0,z:0,w:8,d:14};box(0,-.35,0,8,.5,14,state.used.has('neonLava')?'#1f66d0':'#ff4b23',{emissive:state.used.has('neonLava')?'#5ec8ff':'#ff3b2f',ei:.85});[-2.8,0,2.8].forEach((x,i)=>platform(x,i%2?2:-2,2.35,2.35,state.used.has('glass')?'#d8f6ff':'#a98f6f',{h:.7,transparent:state.used.has('glass'),opacity:state.used.has('glass')?.65:1}));if(state.used.has('welcome'))sign(-12,-4.5,'歡迎來玩！');state.goal={x:13,z:0,open:state.used.size>0};startPos(-13,0,.5);addFlag(13,0,state.goal.open);[-2.8,0,2.8].forEach((x,i)=>addCoin(x,i%2?2:-2,1.35));}
function buildMoving(){platform(-11,0,10,14,'#4cbb5e');platform(11,0,10,14,'#aab4bf');state.lava={x:0,z:0,w:12,d:14};box(0,-.55,0,12,.35,14,'#5db4e8',{rough:.5});const p=platform(state.platformX,0,state.used.has('wide')?6.2:3.2,4,state.used.has('neon')?'#8b5cf6':'#ffc93c',{h:.75,moving:true,id:'moving',emissive:state.used.has('neon')?'#8b5cf6':'#000000',ei:state.used.has('neon')?.55:0});state.movingPlatform=p;if(state.used.has('checkpoint')){const cp=platform(0,4.6,2.6,2.6,'#eefaf1',{h:.5,id:'checkpoint'});const sp=labelSprite('檢查點','#4cbb5e');sp.position.set(0,2.2,4.6);world.add(sp);state.checkpoint={x:0,z:4.6,y:cp.top};}state.goal={x:13,z:0,open:true};startPos(-13,0,.5);addFlag(13,0,true);}
function buildBridge(){platform(-13,0,6,14,'#4cbb5e');platform(13,0,6,14,'#aab4bf');state.lava={x:0,z:0,w:20,d:14};box(0,-.55,0,20,.35,14,'#49a9de');state.bridgeTiles=[];for(let i=0;i<6;i++){const x=-7.5+i*3;const p=platform(x,0,2.3,3.3,state.used.has('ice')?'#d2f7ff':'#d8e0e7',{h:.55,transparent:state.used.has('ice'),opacity:state.used.has('ice')?.72:1,id:'bridge'+i});p.index=i;state.bridgeTiles.push(p);}if(state.used.has('safe'))platform(0,5.2,20,2.2,'#c8d0d8',{h:.45,id:'safe'});state.goal={x:14,z:0,open:true};startPos(-14,0,.5);addFlag(14,0,true);}
function buildLaser(){const floorColor=state.used.has('cyber')?'#232b45':'#d7e3ee';platform(0,0,30,18,floorColor);if(state.used.has('hint')){[-6,0,6].forEach((x,i)=>{const a=labelSprite(['紅 ①','藍 ②','黃 ③'][i],['#ef4444','#3aa7e8','#d5a600'][i]);a.position.set(x,1.6,[-4,4,-4][i]);world.add(a);});}const data=[[-6,-4,'red','#ef4444','紅'],[0,4,'blue','#3aa7e8','藍'],[6,-4,'yellow','#ffc93c','黃']];data.forEach(d=>{const m=box(d[0],.65,d[1],1.5,.35,1.5,d[3],{emissive:d[3],ei:.35});const l=labelSprite(d[4],d[3]);l.position.set(d[0],1.8,d[1]);world.add(l);buttons.push({x:d[0],z:d[1],key:d[2],mesh:m,hit:false});});[-2,4,9].forEach((x,i)=>{if(i===2&&state.used.has('oneOff'))return;const m=box(x,2.6,0,.18,5.2,15,'#ff334f',{emissive:'#ff334f',ei:1});lasers.push({x,mesh:m,index:i,active:true});});state.goal={x:13,z:0,open:false};startPos(-13,0,.5);addFlag(13,0,false);}
function buildMaze(){platform(0,0,30,20,state.used.has('forest')?'#9cd7a8':'#edf3f8');const c=state.used.has('forest')?'#417b4a':'#68758b';[[-9,-3,.7,13],[-5,4,8,.7],[-4,-3,.7,11],[0,-4,8,.7],[2,3,.7,12],[6,5,8,.7],[8,-2,.7,10]].forEach(w=>wall(w[0],w[1],w[2],w[3],2.5,c));if(state.used.has('trail'))[[-12,0],[-11,7],[-6,7],[-6,1],[-1,1],[-1,7],[5,7],[5,0],[12,0]].forEach((q,i)=>{const m=box(q[0],.58,q[1],.45,.08,.75,i%2?'#ffc93c':'#ff9d31',{emissive:'#ffc93c',ei:.35});m.rotation.y=i%2?.4:-.4;});[[-11,-6],[-7,6],[-1,-1],[5,6],[10,-5]].forEach(q=>addCoin(q[0],q[1]));state.goal={x:13,z:0,open:false};startPos(-13,0,.5);addFlag(13,0,false);const hud=labelSprite('金幣 0 / '+state.goalCoins,'#22283b');hud.position.set(0,5,-8);world.add(hud);state.coinHud=hud;}
function buildChase(){platform(0,0,30,20,state.used.has('space')?'#141b35':'#dce9f1');if(state.used.has('space')){for(let i=0;i<80;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.035,4,4),mat('#ffffff',{emissive:'#ffffff',ei:1}));s.position.set((i*7.7)%30-15,4+(i%5),((i*11.3)%20)-10);world.add(s);}}if(state.used.has('safeZone')){[[-5,-4],[4,5]].forEach(q=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(2.4,2.4,.12,32),mat('#4cbb5e',{transparent:true,opacity:.5,emissive:'#4cbb5e',ei:.35}));m.position.set(q[0],.58,q[1]);world.add(m);const l=labelSprite('安全區','#3a9c4a');l.position.set(q[0],2,q[1]);world.add(l);});}const core=new THREE.Mesh(new THREE.OctahedronGeometry(1),mat('#ffc93c',{emissive:'#ffc93c',ei:1,metal:.3}));core.position.set(0,1.65,0);world.add(core);state.coreMesh=core;buildEnemy();state.enemy.speed=state.used.has('enemySlow')?2.1:3.4;state.playerBoost=state.used.has('boost');state.safeZones=state.used.has('safeZone');state.goal={x:13,z:0,open:false};startPos(-13,0,.5);addFlag(13,0,false);}
function highestSupport(x,z){let best=null;for(const p of platforms){if(!p.active)continue;if(Math.abs(x-p.x)<=p.w/2-playerRadius*.15&&Math.abs(z-p.z)<=p.d/2-playerRadius*.15){if(!best||p.top>best.top)best=p;}}return best;}
function wallHit(x,z){for(const w of walls){if(!w.active)continue;if(Math.abs(x-w.x)<w.w/2+playerRadius&&Math.abs(z-w.z)<w.d/2+playerRadius)return true;}return false;}
function movePlayer(dt){const p=state.player;let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dz=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);const len=Math.hypot(dx,dz)||1;dx/=len;dz/=len;let speed=p.speed;if(levels[idx].type==='chase'&&state.playerBoost&&keys[' '])speed=11;if(state.boostTime>0){speed=12;state.boostTime-=dt;}if(dx||dz){const nx=p.x+dx*speed*dt;if(!wallHit(nx,p.z))p.x=nx;const nz=p.z+dz*speed*dt;if(!wallHit(p.x,nz))p.z=nz;p.yaw=Math.atan2(dx,dz);}const on=highestSupport(p.x,p.z);if(on&&on.speedPad)state.boostTime=1.25;if(p.grounded&&p.on&&p.on.moving){p.x+=p.on.dx;p.z+=p.on.dz;}const prevY=p.y;p.vy-=20*dt;p.y+=p.vy*dt;const support=highestSupport(p.x,p.z);if(support&&p.vy<=0&&p.y<=support.top+.12&&prevY>=support.top-.25){p.y=support.top;p.vy=0;p.grounded=true;p.on=support;}else if(!support||p.y>support.top+.16){p.grounded=false;p.on=null;}if(p.y<-7)return die('你掉出地板了。');if(state.lava&&Math.abs(p.x-state.lava.x)<state.lava.w/2&&Math.abs(p.z-state.lava.z)<state.lava.d/2&&p.y<.15&&!support)return die(levels[idx].type==='lava'?'岩漿太寬，真的跳不過去。現在可以停止測試，選一個方法修理它！':'你掉進危險區域了。');if(levels[idx].type==='laser')updateButtonsAndLasers();collectCoins();checkGoal();if(levels[idx].type==='chase')updateChase(dt);}
function updateDynamic(dt){if(levels[idx].type==='moving'&&state.movingPlatform){const p=state.movingPlatform,old=p.x;state.platformX+=state.platformDir*(state.used.has('slow')?2.1:4.4)*dt;if(state.platformX>4.7||state.platformX<-4.7){state.platformDir*=-1;state.platformX=Math.max(-4.7,Math.min(4.7,state.platformX));}p.x=state.platformX;p.dx=p.x-old;p.mesh.position.x=p.x;p.lip.position.x=p.x;}if(levels[idx].type==='bridge'&&state.bridgeTiles){state.bridgeTiles.forEach((p,i)=>{const period=state.used.has('long')?2.8:2,phase=state.used.has('together')?0:i*.42,visible=((state.t+phase)%period)<(state.used.has('long')?2.05:.95);p.active=visible;p.mesh.visible=visible;p.lip.visible=visible;});}if(levels[idx].type==='laser'){lasers.forEach(l=>{const active=((state.t+l.index*.35)%state.laserPeriod)<state.laserPeriod*.58;l.active=active;l.mesh.visible=active;});}if(coins.length)coins.forEach((c,i)=>{if(!c.taken){c.group.rotation.y+=dt*2.3;c.group.position.y=c.y+Math.sin(state.t*2.2+i)*.12;}});if(state.coreMesh){state.coreMesh.rotation.y+=dt*1.8;state.coreMesh.rotation.x+=dt*.8;state.coreMesh.position.y=1.65+Math.sin(state.t*2)*.18;}}
function updateButtonsAndLasers(){const p=state.player;buttons.forEach((b,i)=>{if(b.hit)return;if(Math.hypot(p.x-b.x,p.z-b.z)<1.3){const expected=['red','blue','yellow'][state.order.length];if(b.key===expected){b.hit=true;state.order.push(b.key);b.mesh.scale.y=.12;b.mesh.material.emissiveIntensity=1;msg('條件 '+state.order.length+' 成立：已啟動<b>'+['紅','藍','黃'][i]+'色按鈕</b>。');if(state.order.length===3){state.goal.open=true;setFlag(true);msg('三個條件全部成立，<b>密碼門解鎖</b>！');}}else{state.order=[];buttons.forEach(x=>{x.hit=false;x.mesh.scale.y=1});msg('順序不對，密碼重新歸零。請按照 <b>紅 → 藍 → 黃</b>。');}}});for(const l of lasers){if(l.active&&Math.abs(p.x-l.x)<.6&&Math.abs(p.z)<7.5)return die('你碰到雷射了。');}}
function updateChase(dt){const p=state.player;if(!state.hasCore&&Math.hypot(p.x-state.core.x,p.z-state.core.z)<1.45){state.hasCore=true;state.coreMesh.visible=false;state.goal.open=true;setFlag(true);msg('你拿到<b>能源核心</b>了！出口條件成立，快逃出去。');}const safe=state.safeZones&&((p.x+5)**2+(p.z+4)**2<2.4**2||(p.x-4)**2+(p.z-5)**2<2.4**2);if(!safe){const a=Math.atan2(p.x-state.enemy.x,p.z-state.enemy.z);state.enemy.x+=Math.sin(a)*state.enemy.speed*dt;state.enemy.z+=Math.cos(a)*state.enemy.speed*dt;}enemyGroup.position.set(state.enemy.x,.5,state.enemy.z);enemyGroup.rotation.y=Math.atan2(p.x-state.enemy.x,p.z-state.enemy.z);if(Math.hypot(p.x-state.enemy.x,p.z-state.enemy.z)<1.3)die('方塊怪物追上你了。');}
function collectCoins(){const p=state.player;coins.forEach(c=>{if(c.taken)return;if(Math.hypot(p.x-c.x,p.z-c.z)<1.15&&Math.abs(p.y-c.y)<2){c.taken=true;c.group.visible=false;state.coins++;msg('你收集到一枚金幣，目前共 <b>'+state.coins+'</b> 枚。');if(levels[idx].type==='maze'){state.goal.open=state.coins>=state.goalCoins;setFlag(state.goal.open);if(state.coinHud){world.remove(state.coinHud);state.coinHud=labelSprite('金幣 '+state.coins+' / '+state.goalCoins,'#22283b');state.coinHud.position.set(0,5,-8);world.add(state.coinHud);}}}});}
function checkGoal(){const p=state.player;if(Math.hypot(p.x-state.goal.x,p.z-state.goal.z)<1.65){if(levels[idx].type==='styleRun'&&state.used.size<1){if(!state.lockNotice){state.lockNotice=true;msg('已經跑到終點附近了！先停止測試，完成<b>至少一個風格改造</b>，作品才會解鎖。');}return;}if(!state.goal.open)return;if(levels[idx].type==='lava'&&!['lavaNarrow','jumpPad','speedPad'].some(x=>state.used.has(x)))return;win(winText());}}
function winText(){return['碰到旗子了！你完成第一塊地板。','你先測試，再選方案修好了岩漿關卡。','你加入自己的風格並完成第一個跑酷作品。','你成功搭上移動平台到達終點。','你掌握了計時器節奏，安全通過消失橋。','三個條件按照正確順序成立，密碼門已開啟。','金幣計數器達標，迷宮出口打開了。','你修改了 NPC 與玩家能力，完成終極追逐關卡。'][idx];}
function updateAvatar(dt){const p=state.player;if(!avatar)return;avatar.position.set(p.x,p.y,p.z);let da=p.yaw-avatar.rotation.y;da=Math.atan2(Math.sin(da),Math.cos(da));avatar.rotation.y+=da*Math.min(1,dt*12);const moving=running&&(keys.ArrowRight||keys.ArrowLeft||keys.ArrowUp||keys.ArrowDown||keys.w||keys.a||keys.s||keys.d);const sw=moving?Math.sin(state.t*10)*.55:0;armL.rotation.x=sw;armR.rotation.x=-sw;legL.rotation.x=-sw;legR.rotation.x=sw;avatar.position.y+=moving&&p.grounded?Math.abs(Math.sin(state.t*10))*.06:0;}
function jump(){if(!running||won)return;if(levels[idx].type==='chase'&&state.playerBoost)return;const p=state.player;if(p.grounded){p.vy=8.8;p.grounded=false;p.on=null;}}
function resetPlayer(){const cp=state.checkpoint;if(cp)startPos(cp.x,cp.z,cp.y);else{const t=levels[idx].type;if(t==='floor'){const w=state.used.has('tinyPad')?7:state.used.has('skyBig')?24:state.used.has('prairie')?22:18;startPos(-w/2+2,0,.5);}else if(t==='lava')startPos(-state.gap/2-9,0,.5);else startPos(-13,0,.5);}if(enemyGroup){state.enemy.x=8;state.enemy.z=-5;enemyGroup.position.set(8,.5,-5);}state.player.vy=0;}
function die(text){if(!running)return;state.dead++;flash();resetPlayer();if(levels[idx].type==='lava'&&!state.repairUnlocked){state.repairUnlocked=true;state.firstFail=true;renderOptions();msg('<b>找到問題了！</b>現在從下面選一個修復方法，再按 ▶ 玩玩看重新測試。');}else msg(text+' 我把你送回起點，修改規則後再試一次。');}
function flash(){const f=$('#redflash');f.classList.remove('flash');void f.offsetWidth;f.classList.add('flash');}
function win(text){if(won)return;won=true;running=false;wins++;setMode(false);setHow(4);$('#toastText').textContent=text;$('#toast').classList.add('show');$('#nextBtn').hidden=false;$('#nextBtn').textContent=idx===levels.length-1?'查看學習成果 →':'前往第 '+levels[idx+1].no+' 關 →';msg('測試成功！你完成了<b>改世界 → 玩玩看 → 驗證結果</b>的設計循環。');}
function assistantIcon(){return '<svg class="rav" aria-hidden="true"><use href="#rhead"/></svg>';}
function msg(html,kid=false){const d=document.createElement('div');d.className='dk-m '+(kid?'kid':'r');d.innerHTML='<span class="av">'+assistantIcon()+'</span><div class="bub">'+html+'</div>';$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight;}
function renderOptions(){let box=$('#options');if(!box){box=document.createElement('div');box.className='pchips';box.id='options';$('#chat').appendChild(box);}box.innerHTML='';const L=levels[idx];if(L.type==='lava'&&!state.repairUnlocked){const n=document.createElement('div');n.className='taskcard';n.innerHTML='<b>👇 先測試看看</b><p>這一關要先親自發現問題，失敗一次後才會出現修復選項。</p>';box.appendChild(n);return;}L.options.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='pchip '+(o[3]||'');b.innerHTML=o[1];if(state.used.has(o[0]))b.classList.add('used');b.disabled=running||state.used.has(o[0]);b.onclick=()=>applyOption(o,b);box.appendChild(b);});}
function applyOption(o,b){if(running||state.used.has(o[0]))return;state.used.add(o[0]);totalMods++;msg(o[1],true);if(o[0]==='skyBig'||o[0]==='prairie'||o[0]==='tinyPad'){}else if(o[0]==='lavaNarrow')state.lavaNarrow=true;else if(o[0]==='jumpPad')state.jumpPad=true;else if(o[0]==='speedPad')state.speedPad=true;else if(o[0]==='poison')state.style='poison';else if(o[0]==='glass')state.glass=true;else if(o[0]==='neonLava')state.neonLava=true;else if(o[0]==='welcome')state.welcome=true;else if(o[0]==='slow')state.platformSpeed=2.1;else if(o[0]==='wide')state.platformW=6.2;else if(o[0]==='checkpoint')state.checkpoint={x:0,z:4.6,y:.75};else if(o[0]==='neon')state.style='neon';else if(o[0]==='long')state.bridgeLong=true;else if(o[0]==='together')state.bridgeTogether=true;else if(o[0]==='safe')state.safe=true;else if(o[0]==='ice')state.style='ice';else if(o[0]==='hint')state.showHint=true;else if(o[0]==='laserSlow')state.laserPeriod=2.2;else if(o[0]==='oneOff')state.disabledLaser=true;else if(o[0]==='cyber')state.style='cyber';else if(o[0]==='goal3')state.goalCoins=3;else if(o[0]==='trail')state.showTrail=true;else if(o[0]==='radar')state.radar=true;else if(o[0]==='forest')state.style='forest';else if(o[0]==='enemySlow')state.enemy.speed=2.1;else if(o[0]==='boost')state.playerBoost=true;else if(o[0]==='safeZone')state.safeZones=true;else if(o[0]==='space')state.style='space';$('#counter').textContent='🎨 '+state.used.size;$('#sceneCount').textContent=state.used.size;msg('<b>修改完成！</b>'+o[2]+' 現在可以按綠色 <b>▶ 玩玩看</b> 測試。');setHow(2);buildWorld(.9);renderOptions();}
function setHow(n){for(let i=1;i<=4;i++)$('#how'+i).classList.toggle('on',i===n);}
function setMode(v){running=v;$('#mode').textContent=v?'🎮 遊玩模式':'🛠 設計模式';$('#mode').className='modebadge '+(v?'play':'design');$('#playBtn').textContent=v?'⏹ 停止測試':'▶ 玩玩看';$('#playBtn').className='dk-btn '+(v?'dk-btn-lava':'dk-btn-grass');renderOptions();setHow(v?3:state.used.size?2:1);}
function progress(){const p=$('#progress');p.innerHTML='';levels.forEach((l,i)=>{const s=document.createElement('span');s.className='wz'+(i===idx?' on':i<idx?' done':'');s.textContent='第 '+l.no+' 關';p.appendChild(s);if(i<levels.length-1){const a=document.createElement('span');a.className='wz-arw';a.textContent='▸';p.appendChild(a);}});}
function renderLevel(){const L=levels[idx];progress();$('#levelTitle').innerHTML='<b>第 '+L.no+' 關</b> ・ '+L.title;$('#assistantSub').textContent='第 '+L.no+' 關 · '+L.title;$('#counter').textContent='🎨 0';$('#sceneCount').textContent='0';$('#chat').innerHTML='<div class="taskcard"><b>🎯 任務：'+L.task+'</b><p>'+L.second+'</p></div><span class="dk-concept">🧠 這關偷偷在學：'+L.concept+'</span><div class="dk-m r"><span class="av">'+assistantIcon()+'</span><div class="bub">'+L.intro+'</div></div><div class="dk-m r"><span class="av">'+assistantIcon()+'</span><div class="bub">'+L.second+'</div></div><div class="pchips" id="options"></div>';renderOptions();$('#splashTag').textContent=L.tag;$('#splashTitle').textContent=L.title;$('#splashGoal').innerHTML=L.splash;$('#splash').classList.remove('closed');$('#toast').classList.remove('show');$('#nextBtn').hidden=true;levelStarted=false;setMode(false);buildWorld(4.5);}
function showResult(){$('#gameShell').hidden=true;$('#progress').hidden=true;$('#levelTitle').hidden=true;$('#nextBtn').hidden=true;$('#result').hidden=false;$('#statCommands').textContent=totalMods;$('#statWins').textContent=wins;scrollTo({top:0,behavior:'smooth'});}
function nextLevel(){if(idx<levels.length-1){idx++;initState();renderLevel();scrollTo({top:0,behavior:'smooth'});}else showResult();}
function restart(){idx=0;totalMods=0;wins=0;$('#result').hidden=true;$('#gameShell').hidden=false;$('#progress').hidden=false;$('#levelTitle').hidden=false;initState();renderLevel();scrollTo({top:0,behavior:'smooth'});}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());state.t+=dt;const elapsed=performance.now()-buildAt;if(elapsed<780){const q=1-Math.pow(1-Math.min(1,elapsed/780),3);world.position.y=buildFrom*(1-q);}else world.position.y=0;if(running&&!won){updateDynamic(dt);movePlayer(dt);}else updateDynamic(dt);updateAvatar(dt);updateCamera();renderer.render(scene,camera);}
setup3D();
$('#startLevel').onclick=()=>{levelStarted=true;$('#splash').classList.add('closed');buildAt=performance.now();buildFrom=1.8;world.position.y=1.8;msg('世界蓋好了！先選一句改造，或直接按 <b>▶ 玩玩看</b>。');};
$('#playBtn').onclick=()=>{if(won)return;if(!levelStarted){$('#splash').classList.add('closed');levelStarted=true;}if(running){setMode(false);msg('已停止測試，可以繼續改造世界。');}else{setMode(true);msg('進入遊玩模式。用方向鍵／WASD 移動，空白鍵跳躍。');}};
$('#resetBtn').onclick=()=>{resetPlayer();state.order=[];state.coins=0;state.hasCore=false;coins.forEach(c=>{c.taken=false;c.group.visible=true});buttons.forEach(b=>{b.hit=false;b.mesh.scale.y=1});if(state.coreMesh)state.coreMesh.visible=true;state.goal.open=levels[idx].type!=='laser'&&levels[idx].type!=='maze'&&levels[idx].type!=='chase';setFlag(state.goal.open);msg('位置與本次測試資料已重設，世界改造會保留。');};
$('#nextBtn').onclick=nextLevel;$('#replayBtn').onclick=restart;
addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=true;if(e.code==='Space'){jump();e.preventDefault();}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();},{passive:false});
addEventListener('keyup',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=false;});
initState();renderLevel();animate();
})();
